name: 我的第一个测试流水线
on: push
jobs:
    build-test:
         runs-on: ubuntu-latest
         steps:
              - name: 这是第一个步骤
                id: step1
                run: |
                    echo "myoutput=这是我的输出" >> "$GITHUB_OUTPUT"
              - name: step2
                run: echo "${{ steps.step1.outputs.myoutput }}"