name: 我的第一个测试流水线
on: 
  push:
    branches: 
      - main
  workflow_dispatch: #手动触发
jobs:
    build-test:
         runs-on: ubuntu-latest
         
         steps:
              - name: 分支检查
                if: github.ref_name != 'main'
                run: |
                  echo "警告 当前分支 ${{github.ref_name}} 不能自动执行Ci流程"
              - name: 这是第一个步骤
                id: step-1
                if: github.ref_name == 'main'
                run: |
                    echo "myoutput=这是我的输出" >> "$GITHUB_OUTPUT"
              - name: step2
                run: echo "${{ steps.step-1.outputs.myoutput }}"